ASSEMBLER=dasm

hello.prg: 4-hello/hello.a
	$(ASSEMBLER) 4-hello/hello.a -ohello.prg -lhello.lst -shello.sym

vsync.prg: 5-vsync/vsync.a
	$(ASSEMBLER) 5-vsync/vsync.a -ovsync.prg -lvsync.lst -svsync.sym

playfield.prg: 6-playfield/playfield.a
	$(ASSEMBLER) 6-playfield/playfield.a -oplayfield.prg -lplayfield.lst -splayfield.sym

sprite.prg: 7-sprite/sprite.a
	$(ASSEMBLER) 7-sprite/sprite.a -osprite.prg -lsprite.lst -ssprite.sym

colorsprites.prg: 8-colorsprites/colorsprites.a
	$(ASSEMBLER) 8-colorsprites/colorsprites.a -ocolorsprites.prg -lcolorsprites.lst -scolorsprites.sym

timing2.prg: 9-timing2/timing2.a
	$(ASSEMBLER) 9-timing2/timing2.a -otiming2.prg -ltiming2.lst -stiming2.sym

missiles.prg: 10-missiles/missiles.a
	$(ASSEMBLER) 10-missiles/missiles.a -omissiles.prg -lmissiles.lst -smissiles.sym

sethorizpos.prg: 11-sethorizpos/sethorizpos.a
	$(ASSEMBLER) 11-sethorizpos/sethorizpos.a -osethorizpos.prg -lsethorizpos.lst -ssethorizpos.sym

piatimer.prg: 12-piatimer/piatimer.a
	$(ASSEMBLER) 12-piatimer/piatimer.a -opiatimer.prg -lpiatimer.lst -spiatimer.sym

controls.prg: 13-controls/controls.a
	$(ASSEMBLER) 13-controls/controls.a -ocontrols.prg -lcontrols.lst -scontrols.sym

complexscene.prg: 15-complexscene/complexscene.a
	$(ASSEMBLER) 15-complexscene/complexscene.a -ocomplexscene.prg -lcomplexscene.lst -scomplexscene.sym

complexscene2.prg: 16-complexscene2/complexscene2.a
	$(ASSEMBLER) 16-complexscene2/complexscene2.a -ocomplexscene2.prg -lcomplexscene2.lst -scomplexscene2.sym

scoreboard.prg: 18-scoreboard/scoreboard.a
	$(ASSEMBLER) 18-scoreboard/scoreboard.a -oscoreboard.prg -lscoreboard.lst -sscoreboard.sym

collisions.prg: 19-collisions/collisions.a
	$(ASSEMBLER) 19-collisions/collisions.a -ocollisions.prg -lcollisions.lst -scollisions.sym

bitmap.prg: 20-bitmap/bitmap.a
	$(ASSEMBLER) 20-bitmap/bitmap.a -obitmap.prg -lbitmap.lst -sbitmap.sym

brickgame.prg: 21-brickgame/brickgame.a
	$(ASSEMBLER) 21-brickgame/brickgame.a -obrickgame.prg -lbrickgame.lst -sbrickgame.sym

bigsprite.prg: 22-bigsprite/bigsprite.a
	$(ASSEMBLER) 22-bigsprite/bigsprite.a -obigsprite.prg -lbigsprite.lst -sbigsprite.sym

tinytext.prg: 23-tinytext/tinyfonts2.a
	$(ASSEMBLER) 23-tinytext/tinyfonts2.a -otinytext.prg -ltinytext.lst -stinytext.sym

score6.prg: 24-score6/score6.a
	$(ASSEMBLER) 24-score6/score6.a -oscore6.prg -lscore6.lst -sscore6.sym

retrigger.prg: 26-retrigger/retrigger.a
	$(ASSEMBLER) 26-retrigger/retrigger.a -oretrigger.prg -lretrigger.lst -sretrigger.sym

multisprites.prg: 28-multisprites/multisprite3.a
	$(ASSEMBLER) 28-multisprites/multisprite3.a -omultisprites.prg -lmultisprites.lst -smultisprites.sym

procgen1.prg: 30-procgen1/procgen1.a
	$(ASSEMBLER) 30-procgen1/procgen1.a -oprocgen1.prg -lprocgen1.lst -sprocgen1.sym

lines.prg: 31-lines/lines.a
	$(ASSEMBLER) 31-lines/lines.a -olines.prg -llines.lst -slines.sym

musicplayer.prg: 32-musicplayer/musicplayer.a
	$(ASSEMBLER) 32-musicplayer/musicplayer.a -omusicplayer.prg -lmusicplayer.lst -smusicplayer.sym

road.prg: 33-road/road.a
	$(ASSEMBLER) 33-road/road.a -oroad.prg -lroad.lst -sroad.sym

bankswitching.prg: 35-bankswitching/bankswitching.a
	$(ASSEMBLER) 35-bankswitching/bankswitching.a -obankswitching.prg -lbankswitching.lst -sbankswitching.sym

wavetable.prg: 36-wavetable/wavetable.a
	$(ASSEMBLER) 36-wavetable/wavetable.a -owavetable.prg -lwavetable.lst -swavetable.sym

fracpitch.prg: fracpitch/fracpitch.a
	$(ASSEMBLER) fracpitch/fracpitch.a -ofracpitch.prg -lfracpitch.lst -sfracpitch.sym

pal.prg: pal/pal.a
	$(ASSEMBLER) pal/pal.a -opal.prg -lpal.lst -spal.sym

all: hello.prg vsync.prg playfield.prg sprite.prg colorsprites.prg timing2.prg missiles.prg sethorizpos.prg piatimer.prg controls.prg complexscene.prg complexscene2.prg scoreboard.prg collisions.prg bitmap.prg brickgame.prg bigsprite.prg tinytext.prg score6.prg retrigger.prg multisprites.prg procgen1.prg lines.prg musicplayer.prg road.prg bankswitching.prg wavetable.prg fracpitch.prg pal.prg
